'use client';
import { motion } from 'framer-motion';
import { TextScramble } from './TextScramble';
import { NavBar } from './NavBar';

export function Hero() {
  return (
    <main className="min-h-screen bg-black text-white">
      <NavBar />
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center justify-center overflow-hidden bg-black pt-16">
        {/* Grid background */}
        <div className="absolute inset-0 bg-[linear-gradient(to_right,#ffffff06_1px,transparent_1px),linear-gradient(to_bottom,#ffffff06_1px,transparent_1px)] bg-[size:72px_72px]" />
        {/* Radial vignette */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_70%_60%_at_50%_50%,transparent_30%,#000_100%)]" />

        <div className="relative z-10 w-full max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
          <div className="flex flex-col items-center gap-10">

            {/* Badge */}
            <motion.div
              initial={{ opacity: 0, y: -8 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.1, duration: 0.5 }}
              className="inline-flex items-center gap-2 px-4 py-1.5 border border-white/10 bg-white/[0.03]"
              style={{ fontFamily: 'var(--font-jua)' }}
            >
              <motion.svg
                width="8" height="8" viewBox="0 0 8 8" fill="none"
                animate={{ opacity: [1, 0.3, 1] }}
                transition={{ duration: 1.5, repeat: Infinity }}
              >
                <circle cx="4" cy="4" r="3.5" fill="#FF0000"/>
              </motion.svg>
              <span className="text-white/35 text-[10px] tracking-[0.25em] uppercase">
                AI · YouTube Thumbnail Generator
              </span>
            </motion.div>

            {/* Title */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.8, delay: 0.2 }}
              className="text-center space-y-3"
            >
              <TextScramble
                as="h1"
                className="text-5xl sm:text-6xl md:text-8xl text-white leading-tight"
                duration={1.4}
                speed={0.05}
                style={{ fontFamily: 'var(--font-jua)' }}
              >
                uksnote..
              </TextScramble>
              <TextScramble
                as="p"
                className="text-sm sm:text-base text-white/35 tracking-[0.2em] uppercase"
                duration={1.1}
                speed={0.04}
                style={{ fontFamily: 'var(--font-jua)' }}
              >
                Generated by uksnote..
              </TextScramble>
            </motion.div>

            {/* Visual Flow */}
            <motion.div
              initial={{ opacity: 0, y: 32 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.7, duration: 0.9 }}
              className="w-full flex flex-col md:flex-row items-center justify-center gap-2 md:gap-3"
            >
              {/* Step 1: Upload */}
              <div className="flex flex-col items-center gap-2.5">
                <span className="text-[9px] text-white/20 tracking-[0.25em] uppercase" style={{ fontFamily: 'var(--font-jua)' }}>
                  01 · Upload
                </span>
                <motion.div
                  whileHover={{ borderColor: 'rgba(255,255,255,0.3)' }}
                  className="w-52 h-36 border border-dashed border-white/15 bg-white/[0.02] flex flex-col items-center justify-center gap-3 cursor-pointer transition-all group"
                >
                  <svg width="38" height="38" viewBox="0 0 38 38" fill="none" className="text-white/25 group-hover:text-white/50 transition-colors">
                    <path d="M19 25V13" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/>
                    <path d="M13 19L19 13L25 19" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M8 29C8 30.1 8.9 31 10 31H28C29.1 31 30 30.1 30 29" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeOpacity="0.4"/>
                    <rect x="1" y="1" width="36" height="36" rx="2" stroke="currentColor" strokeWidth="1" strokeDasharray="4 3" strokeOpacity="0.3"/>
                  </svg>
                  <span className="text-[10px] text-white/25 tracking-widest uppercase group-hover:text-white/45 transition-colors" style={{ fontFamily: 'var(--font-jua)' }}>
                    이미지 드롭
                  </span>
                </motion.div>
              </div>

              {/* Arrow */}
              <div className="flex items-center justify-center mt-6">
                <motion.svg width="48" height="14" viewBox="0 0 48 14" fill="none"
                  className="hidden md:block"
                  animate={{ x: [0, 5, 0] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                >
                  <path d="M0 7H40M40 7L33 1M40 7L33 13" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </motion.svg>
                <motion.svg width="14" height="32" viewBox="0 0 14 32" fill="none"
                  className="block md:hidden"
                  animate={{ y: [0, 4, 0] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
                >
                  <path d="M7 0V24M7 24L1 17M7 24L13 17" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </motion.svg>
              </div>

              {/* Step 2: AI */}
              <div className="flex flex-col items-center gap-2.5">
                <span className="text-[9px] text-white/20 tracking-[0.25em] uppercase" style={{ fontFamily: 'var(--font-jua)' }}>
                  02 · AI Process
                </span>
                <div className="w-52 h-36 border border-white/15 bg-white/[0.02] flex flex-col items-center justify-center gap-3">
                  <motion.svg width="46" height="46" viewBox="0 0 46 46" fill="none"
                    animate={{ rotate: 360 }}
                    transition={{ duration: 9, repeat: Infinity, ease: 'linear' }}
                  >
                    <circle cx="23" cy="23" r="21" stroke="white" strokeOpacity="0.06" strokeWidth="1"/>
                    <circle cx="23" cy="23" r="13" stroke="white" strokeOpacity="0.05" strokeWidth="1"/>
                    <path d="M23 5L25.8 14.2L35 17L25.8 19.8L23 29L20.2 19.8L11 17L20.2 14.2L23 5Z"
                      stroke="white" strokeOpacity="0.45" strokeWidth="1.2" strokeLinejoin="round"/>
                    <path d="M23 35L24.2 38.8L28 40L24.2 41.2L23 45L21.8 41.2L18 40L21.8 38.8L23 35Z"
                      fill="white" fillOpacity="0.2"/>
                    <circle cx="23" cy="23" r="2" fill="white" fillOpacity="0.35"/>
                  </motion.svg>
                  <div className="flex gap-1.5">
                    {[0, 1, 2].map((i) => (
                      <motion.div
                        key={i}
                        className="w-1 h-1 rounded-full bg-white/35"
                        animate={{ opacity: [0.15, 1, 0.15] }}
                        transition={{ duration: 1.2, repeat: Infinity, delay: i * 0.35 }}
                      />
                    ))}
                  </div>
                </div>
              </div>

              {/* Arrow */}
              <div className="flex items-center justify-center mt-6">
                <motion.svg width="48" height="14" viewBox="0 0 48 14" fill="none"
                  className="hidden md:block"
                  animate={{ x: [0, 5, 0] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                >
                  <path d="M0 7H40M40 7L33 1M40 7L33 13" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </motion.svg>
                <motion.svg width="14" height="32" viewBox="0 0 14 32" fill="none"
                  className="block md:hidden"
                  animate={{ y: [0, 4, 0] }}
                  transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut', delay: 0.5 }}
                >
                  <path d="M7 0V24M7 24L1 17M7 24L13 17" stroke="white" strokeOpacity="0.18" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                </motion.svg>
              </div>

              {/* Step 3: Thumbnail */}
              <div className="flex flex-col items-center gap-2.5">
                <span className="text-[9px] text-white/20 tracking-[0.25em] uppercase" style={{ fontFamily: 'var(--font-jua)' }}>
                  03 · Thumbnail
                </span>
                <div className="w-52 h-36 border border-white/20 bg-white/[0.02] relative overflow-hidden">
                  <svg width="208" height="144" viewBox="0 0 208 144" fill="none" className="absolute inset-0 w-full h-full">
                    {/* Corner brackets */}
                    <path d="M3 13V3H13" stroke="white" strokeOpacity="0.22" strokeWidth="1.5" strokeLinecap="round"/>
                    <path d="M205 13V3H195" stroke="white" strokeOpacity="0.22" strokeWidth="1.5" strokeLinecap="round"/>
                    <path d="M3 131V141H13" stroke="white" strokeOpacity="0.22" strokeWidth="1.5" strokeLinecap="round"/>
                    <path d="M205 131V141H195" stroke="white" strokeOpacity="0.22" strokeWidth="1.5" strokeLinecap="round"/>
                    {/* Text placeholder bars */}
                    <rect x="14" y="104" width="90" height="6" rx="1" fill="white" fillOpacity="0.15"/>
                    <rect x="14" y="116" width="62" height="4" rx="1" fill="white" fillOpacity="0.08"/>
                    {/* Image zone */}
                    <rect x="118" y="16" width="76" height="54" rx="1" fill="white" fillOpacity="0.05" stroke="white" strokeOpacity="0.1" strokeWidth="1"/>
                    <path d="M140 36L148 46L153 40L165 54H125L137 40L140 36Z" fill="white" fillOpacity="0.07"/>
                    {/* 16:9 ratio label */}
                    <text x="104" y="141" textAnchor="middle" fill="white" fillOpacity="0.12" fontSize="7" fontFamily="monospace" letterSpacing="2">16 : 9</text>
                  </svg>
                  {/* YouTube play button */}
                  <motion.div
                    className="absolute inset-0 flex items-center justify-center"
                    animate={{ scale: [1, 1.07, 1] }}
                    transition={{ duration: 2.8, repeat: Infinity, ease: 'easeInOut' }}
                  >
                    <svg width="38" height="38" viewBox="0 0 38 38" fill="none">
                      <rect width="38" height="38" rx="7" fill="#FF0000" fillOpacity="0.85"/>
                      <path d="M15 11L29 19L15 27V11Z" fill="white"/>
                    </svg>
                  </motion.div>
                  {/* Shimmer */}
                  <motion.div
                    className="absolute inset-0 bg-gradient-to-r from-transparent via-white/[0.05] to-transparent -skew-x-12"
                    animate={{ x: ['-120%', '220%'] }}
                    transition={{ duration: 2.2, repeat: Infinity, ease: 'linear', repeatDelay: 2.5 }}
                  />
                </div>
              </div>
            </motion.div>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 1.5, duration: 0.7 }}
              className="flex flex-col sm:flex-row gap-4 items-center"
            >
              <motion.button
                whileHover={{ scale: 1.04, backgroundColor: '#ffffff', color: '#000000' }}
                whileTap={{ scale: 0.96 }}
                className="px-8 py-3 bg-white text-black text-sm tracking-widest uppercase transition-colors"
                style={{ fontFamily: 'var(--font-jua)' }}
              >
                Generate Now
              </motion.button>
              <motion.button
                whileHover={{ scale: 1.04, backgroundColor: '#ffffff10' }}
                whileTap={{ scale: 0.96 }}
                className="px-8 py-3 border border-white/20 text-white text-sm tracking-widest uppercase transition-colors"
                style={{ fontFamily: 'var(--font-jua)' }}
              >
                Learn More
              </motion.button>
            </motion.div>

          </div>
        </div>

        {/* Scroll Indicator */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 2.4, duration: 1 }}
          className="absolute bottom-8 left-1/2 -translate-x-1/2"
        >
          <motion.div
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 2, repeat: Infinity }}
            className="text-white/20"
          >
            <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M19 14l-7 7m0 0l-7-7m7 7V3"/>
            </svg>
          </motion.div>
        </motion.div>
      </section>

      {/* Features Section */}
      <section className="py-24 px-4 bg-black border-t border-white/10">
        <div className="max-w-5xl mx-auto">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-3xl md:text-4xl font-bold text-center mb-16 text-white tracking-tight"
          >
            Features
          </motion.h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-white/10">
            {[
              {
                title: 'Fast',
                description: '최적화된 성능으로 빠른 로딩 속도를 제공합니다',
                icon: '⚡',
              },
              {
                title: 'Modern',
                description: '최신 기술 스택으로 구축된 현대적인 웹 애플리케이션',
                icon: '🚀',
              },
              {
                title: 'Secure',
                description: '보안을 최우선으로 하는 안전한 플랫폼',
                icon: '🔒',
              },
            ].map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.15 }}
                whileHover={{ backgroundColor: '#ffffff0d' }}
                className="p-10 bg-black transition-colors"
              >
                <div className="text-3xl mb-5">{feature.icon}</div>
                <h3 className="text-xl font-bold mb-3 text-white tracking-tight">
                  {feature.title}
                </h3>
                <p className="text-white/50 text-sm leading-relaxed">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-24 px-4 bg-black border-t border-white/10">
        <div className="max-w-3xl mx-auto text-center">
          <motion.h2
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-4xl md:text-5xl font-bold mb-6 text-white tracking-tight"
          >
            시작할 준비가 되셨나요?
          </motion.h2>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.2 }}
            className="text-lg text-white/50 mb-10"
          >
            지금 바로 시작하고 놀라운 경험을 만나보세요
          </motion.p>
          <motion.button
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            className="px-10 py-4 bg-white text-black rounded-none font-semibold text-sm tracking-widest uppercase hover:bg-white/90 transition-colors"
          >
            Get Started Now
          </motion.button>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-8 px-4 bg-black border-t border-white/10">
        <div className="max-w-5xl mx-auto text-center">
          <p className="text-white/30 text-sm tracking-widest uppercase">
            © 2026 uksnote. All rights reserved.
          </p>
        </div>
      </footer>
    </main>
  );
}
